### ISSUE TITLE
Learn MEAN Stack

### ISSUE THREAD

**Issue by NelsonGoosman** [NelsonGoosman/Cpts322_Group_7#3]
We need to begin to learn the different technologies that make up the mean stack. Comment helpful recources under this issue and begin to do small projects that will help us learn.

**Comment by NelsonGoosman** [comment]
Node introduction: https://www.youtube.com/watch?v=ENrzD9HAZK4

**Comment by NelsonGoosman** [comment]
> Node introduction: https://www.youtube.com/watch?v=ENrzD9HAZK4

Another good recource, more comprehensive and ~1hr: https://www.youtube.com/watch?v=TlB_eWDSMt4

**Comment by NelsonGoosman** [comment]
Angular info: https://www.youtube.com/watch?v=k5E2AVpwsko

**Comment by IvanD1061** [comment]
https://youtu.be/DP7TSgc6glc?si=rf0tzf55kbOlUXs4 This video does a great job at explaining the step by step of what MEAN does.
